add_newline = false

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[git_branch]
symbol = "🌱 "
style="bold blue"
truncation_length = 100
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
ahead = "⇡ ${count}"
diverged = "⇕⇡ ${ahead_count} ⇣ ${behind_count}"
behind = "⇣ ${count}"

[python]
symbol = " "
python_binary = "python3"

[gcloud]
disabled = true

[docker_context]
disabled = true
